name: Update Users JSON
on:
  push:
    branches: [ main ]
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate users.json
        run: |
          mkdir -p data
          cat <<EOF > data/users.json
          [
            {
              "username": "${{ secrets.AUTH_USER }}",
              "password": "${{ secrets.AUTH_PASS }}"
            }
          ]
          EOF
      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add data/users.json
          git commit -m "Update users.json from Secrets" || echo "No changes to commit"
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
